### ISSUE TITLE
Upload NetBoxR Prototype to Galaxy

### ISSUE THREAD

**Issue by cannin** [mil2041/netboxr#26]
Next steps for Galaxy: 

- [x] Given the work from #8 upload the prototype to Galaxy 
- [x] ~~For the name put "NetBox (Alpha Testing, Draft Galaxy Tool)"~~

**Comment by sajo25** [comment]
@cannin @mil2041 

I made a [pull request ](https://github.com/bgruening/galaxytools/pull/1229) following [instructions](https://github.com/bgruening/galaxytools) I found online, but I mistakenly wrote "Add netboxr tool (beta version)" instead of "NetBox (Alpha Testing, Draft Galaxy Tool)".

Steps:
1. I forked (and cloned) the following repository: https://github.com/bgruening/galaxytools
2. I made a new branch named netboxr-beta as per [recommendations](https://github.com/bgruening/galaxytools/blob/6a2deb2f38472a2845123bd54e73b6bd115b3a0b/CONTRIBUTING.md)
3. `push origin netboxr-beta`
4. I copied the [netboxr folder ](https://github.com/mil2041/netboxr/commit/c2be3153b883a7233f00c314899a95cf6e9ab689) I have been working in on VirtualBox to the galaxytools/tools directory
5. `git add -all`
6. `git commit -u -m "Add netboxr tool (beta version)"`
7. `git push origin netboxr-beta`
8. [Pull request](https://github.com/bgruening/galaxytools/pull/1229) (linked previously)

The pull request initiates automated tests, some of which have already failed in the case of the netboxr tool. I still have to look into what the issues are and how they can be fixed. After the tool passes the tests and the PR is merged, it is automatically pushed to the Galaxy Tool Shed, after which it can be installed in every Galaxy instance. Additionally, as far as I understand, a bot will automatically create a Docker container for the tool (as explained in the instructions linked previously).

**Comment by sajo25** [comment]
Most recent [PR](https://github.com/bgruening/galaxytools/pull/1233), still waiting to hear back.

**Comment by sajo25** [comment]
@cannin I'm now getting the same error mentioned in the PR when I try to run the tests in VirtualBox (screenshot below). Not sure what the next steps are.

![Screenshot_2022-08-18_01-06-43](https://user-images.githubusercontent.com/28693536/185402180-0daf3c9e-0d51-4f94-9323-c07188e69ab5.png)

**Comment by cannin** [comment]
Try to debug this by using planemo with just the bioconductor-go.db package (and separately, a different bioconductor package with all lower case letters).

**Comment by sajo25** [comment]
@cannin I didn't get to try out your last suggestion, but running `planemo test --biocontainers .` worked today, so I'm assuming the issue with the bioconductor-go.db package has been resolved.

**Comment by sajo25** [comment]
The tests failed again. I've since removed the r-optparse dependency ([commit](https://github.com/bgruening/galaxytools/pull/1233/commits/634d38e2b341051e36e4faa43c02d90bba248c5d)).

**Comment by cannin** [comment]
@sajo25 Did it pass tests without optparse?

**Comment by sajo25** [comment]
@cannin Only locally, I'm still waiting for approval in the [PR](https://github.com/bgruening/galaxytools/pull/1233).

**Comment by sajo25** [comment]
@cannin @mil2041 The checks passed and the PR was merged. netboxr is now available in the Galaxy [ToolShed](https://toolshed.g2.bx.psu.edu/).

**Comment by cannin** [comment]
great! now we need

* [ ] we need a better description: 

Current:
```

The NetBox algorithm identifies candidate cancer-related functional modules using a data-driven, network-based approach that combines prior knowledge with a network clustering algorithm. The network modules are derived de novo, and can be used to identify new functional gene groups that cross the boundaries of curated gene sets.
```

New: 
```
The NetBox algorithm identifies candidate cancer-related functional modules using a data-driven, network-based approach that combines prior knowledge with a network clustering algorithm. The network modules are derived de novo, and can be used to identify new functional gene groups that cross the boundaries of curated gene sets. (Minwei Liu E, Luna A, et al., 2020 PubMed ID: 33137091; Cerami et al., 2010 PubMed ID: 20169195)
```

* [ ] a demonstration (maybe Thursday) on how to use it; now that it is there, I'm not sure how people can use it.

**Comment by sajo25** [comment]
I'm not sure if I will be able to do a demo tomorrow because I'm having trouble accessing the admin interface, which you need in order to install tools from the ToolShed. I might need some help with it first. More information here: https://galaxyproject.org/admin/

**Comment by sajo25** [comment]
@cannin I actually figured it out. The steps are:

1. Registered myself as user 
2. Created galaxy.yml file using galaxy.yml.sample and edited admin_users (and removed #) [(instructions)](https://galaxyproject.org/admin/)
3. Started up Galaxy (Docker)
4. To log in as admin, I used the following credentials:

Email: admin@galaxy.org
Password: password 
[(source)](https://github.com/bgruening/docker-galaxy-stable/blob/master/README.md)

After successfully logging in, the word "Admin" appears in the bar at the top of the screen (screenshot below). Click here and follow instructions for tool installation.

![image](https://user-images.githubusercontent.com/28693536/186538302-c889d7e4-3cf3-4504-9ded-daac55d126e0.png)

To access the tool, click on "Analyze Data".

I'm don't think steps 1 and 2 are necessary for Docker, as I wasn't able to log in as admin using my own credentials, but I included them just in case because that's what I did before trying out the other credentials.

I can demonstrate everything tomorrow!

**Comment by sajo25** [comment]
> great! now we need
> 
> * [ ]  we need a better description:
> 
> Current:
> 
> ```
> 
> The NetBox algorithm identifies candidate cancer-related functional modules using a data-driven, network-based approach that combines prior knowledge with a network clustering algorithm. The network modules are derived de novo, and can be used to identify new functional gene groups that cross the boundaries of curated gene sets.
> ```
> 
> New:
> 
> ```
> The NetBox algorithm identifies candidate cancer-related functional modules using a data-driven, network-based approach that combines prior knowledge with a network clustering algorithm. The network modules are derived de novo, and can be used to identify new functional gene groups that cross the boundaries of curated gene sets. (Liu E, Luna A, et al., 2020 PubMed ID: 33137091; Cerami et al., 2010 PubMed ID: 20169195)
> ```
> 
> * [ ]  a demonstration (maybe Thursday) on how to use it; now that it is there, I'm not sure how people can use it.

I added the first task to Issue #39, and will make a separate issue about the demo.
