### ISSUE TITLE
Add Weights to Edge Betweenness Function

### ISSUE THREAD

**Issue by cannin** [mil2041/netboxr#35]
@cannin @mil2041 As per our last conversation, I am in the process of making the geneConnector function print a message for community detection methods (ebc and lec) that are incompatible with the "weights" parameter. I noticed that in the igraph manual [cluster_edge_betweenness](https://igraph.org/r/doc/cluster_edge_betweenness.html) and [cluster_leading_eigen](https://igraph.org/r/doc/cluster_leading_eigen.html) both accept edge weights. In the geneConnector function, however, we use edge.betweenness.community and leading.eigenvector.community (which do not accept weights) instead. Is there a reason for this?

_Originally posted by @sajo25 in https://github.com/mil2041/netboxr/issues/9#issuecomment-1207902028_

**Comment by cannin** [comment]
You are most likely looking at old documentation for edge.betweenness.community. Any of the functions with underscores should be the same as those with periods. It does look like in the past, the functions did not accept weights. It would be best to switch to using weights if the idea of using weights for stability holds.

**Comment by sajo25** [comment]
@cannin When I use the weights parameter with ebc I get the following warning:

> In edge.betweenness.community(graphOutput, weights = weightsInput) :
> At core/community/edge_betweenness.c:492 : Modularity calculation with weighted edge betweenness community detection might not make sense -- modularity treats edge weights as similarities while edge betwenness treats them as distances.

Should I still add it?

**Comment by mil2041** [comment]
@sajo25 We wrote the netboxr R package when only an older version of igraph package was available. Thus, we used "edge.betweenness.community" and "leading.eigenvector.community" function from igraph package in the geneConnector function. Since there is updated igraph package and function names, you can replace the old functions to new function names. 

1. "edge.betweenness.community" to [cluster_edge_betweenness](https://igraph.org/r/doc/cluster_edge_betweenness.html)
2. "leading.eigenvector.community" to [cluster_leading_eigen](https://igraph.org/r/doc/cluster_leading_eigen.html)

**Comment by cannin** [comment]
Closing since it is possible to try to use weights with edge betweeness though as igraph authors state. It might not be a good idea to do so.
